version: '3.8'

services:
  backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    ports:
      - "8000:9000"
    volumes:
      - ./todo-backend:/var/www
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=task_manager
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=task_manager
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  db_data: