name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: task_manager
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, zip, exif, pcntl, gd, mysql
        coverage: none

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-interaction

    - name: Copy .env
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Execute tests
      run: |
        php artisan migrate --force
        php artisan test